### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by SamTush** [Tracy-miranja/LEADERBOARD#5]
Hi @Tracy-miranja  👋 ,
You have done a good job so far!
There are some issues you still need to work on to make your project work perfectly.

## Highlights 💯 
- All linter checks are passing ✔️ ✔️
- Your PR is professional 👍 

## Issues ♻️ 
![Screenshot 2023-04-17 at 14 50 51](https://user-images.githubusercontent.com/102317741/232476148-bbed1735-cc42-45f8-845b-a1296c3e83c5.png)

-Good job done so far, but there are some missing scripts missing in your project. The command npm start does not work on your project. Please fix this by making sure your webpack was properly installed🙏.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/102317741/232474968-6cb64d95-5e51-432c-8710-604407567ace.png">

Cheer and happy coding 🥂

**Comment by Tracy-miranja** [comment]
Thanks for highlighting the issue.
